# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\design\PopupCookFinish.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_PopupCookFinish(object):
    def setupUi(self, Dialog_PopupCookFinish):
        Dialog_PopupCookFinish.setObjectName("Dialog_PopupCookFinish")
        Dialog_PopupCookFinish.resize(400, 300)
        Dialog_PopupCookFinish.setMinimumSize(QtCore.QSize(400, 300))
        Dialog_PopupCookFinish.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/vending-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_PopupCookFinish.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog_PopupCookFinish)
        self.label.setGeometry(QtCore.QRect(10, 20, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_PopupCookFinish)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_PopupCookFinish)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PopupCookFinish)

    def retranslateUi(self, Dialog_PopupCookFinish):
        _translate = QtCore.QCoreApplication.translate
        Dialog_PopupCookFinish.setWindowTitle(_translate("Dialog_PopupCookFinish", "Cook - Food Vending Machine"))
        self.label.setText(_translate("Dialog_PopupCookFinish", "กรุณารับอาหารและเงินทอน"))
        self.label_2.setText(_translate("Dialog_PopupCookFinish", "ขอบคุณที่ใช้บริการ"))
import icon_rc
