# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\design\PopupCookFood.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_PopupCookFood(object):
    def setupUi(self, Dialog_PopupCookFood):
        Dialog_PopupCookFood.setObjectName("Dialog_PopupCookFood")
        Dialog_PopupCookFood.resize(400, 300)
        Dialog_PopupCookFood.setMinimumSize(QtCore.QSize(400, 300))
        Dialog_PopupCookFood.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/vending-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_PopupCookFood.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog_PopupCookFood)
        self.label.setGeometry(QtCore.QRect(20, 20, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cook_ok = QtWidgets.QPushButton(Dialog_PopupCookFood)
        self.btn_cook_ok.setGeometry(QtCore.QRect(10, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cook_ok.setFont(font)
        self.btn_cook_ok.setObjectName("btn_cook_ok")
        self.btn_cook_no = QtWidgets.QPushButton(Dialog_PopupCookFood)
        self.btn_cook_no.setGeometry(QtCore.QRect(210, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cook_no.setFont(font)
        self.btn_cook_no.setObjectName("btn_cook_no")
        self.label_2 = QtWidgets.QLabel(Dialog_PopupCookFood)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_timer = QtWidgets.QLabel(Dialog_PopupCookFood)
        self.lbl_timer.setGeometry(QtCore.QRect(230, 90, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_timer.setObjectName("lbl_timer")

        self.retranslateUi(Dialog_PopupCookFood)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PopupCookFood)

    def retranslateUi(self, Dialog_PopupCookFood):
        _translate = QtCore.QCoreApplication.translate
        Dialog_PopupCookFood.setWindowTitle(_translate("Dialog_PopupCookFood", "Cook - Food Vending Machine"))
        self.label.setText(_translate("Dialog_PopupCookFood", "คุณต้องการอุ่นอาหารหรือไม่"))
        self.btn_cook_ok.setText(_translate("Dialog_PopupCookFood", "อุ่นอาหาร"))
        self.btn_cook_no.setText(_translate("Dialog_PopupCookFood", "ไม่"))
        self.label_2.setText(_translate("Dialog_PopupCookFood", "เวลาอุ่นโดยประมาณ"))
        self.lbl_timer.setText(_translate("Dialog_PopupCookFood", "3 นาที"))
import icon_rc
