# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\design\PopupReceiveCoin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_PopupReciveCoin(object):
    def setupUi(self, Dialog_PopupReciveCoin):
        Dialog_PopupReciveCoin.setObjectName("Dialog_PopupReciveCoin")
        Dialog_PopupReciveCoin.resize(400, 300)
        Dialog_PopupReciveCoin.setMinimumSize(QtCore.QSize(400, 300))
        Dialog_PopupReciveCoin.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/vending-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_PopupReciveCoin.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(Dialog_PopupReciveCoin)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog_PopupReciveCoin)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PopupReciveCoin)

    def retranslateUi(self, Dialog_PopupReciveCoin):
        _translate = QtCore.QCoreApplication.translate
        Dialog_PopupReciveCoin.setWindowTitle(_translate("Dialog_PopupReciveCoin", "Coin - Food Vending Machine"))
        self.label_3.setText(_translate("Dialog_PopupReciveCoin", "กรุณารับเงินทอน"))
import icon_rc
