# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\design\TimerCook.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_TimerCook(object):
    def setupUi(self, Dialog_TimerCook):
        Dialog_TimerCook.setObjectName("Dialog_TimerCook")
        Dialog_TimerCook.resize(400, 300)
        Dialog_TimerCook.setMinimumSize(QtCore.QSize(400, 300))
        Dialog_TimerCook.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/vending-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_TimerCook.setWindowIcon(icon)
        self.progressBar = QtWidgets.QProgressBar(Dialog_TimerCook)
        self.progressBar.setGeometry(QtCore.QRect(10, 240, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Dialog_TimerCook)
        self.label.setGeometry(QtCore.QRect(10, 20, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblTimer = QtWidgets.QLabel(Dialog_TimerCook)
        self.lblTimer.setGeometry(QtCore.QRect(10, 90, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblTimer.setFont(font)
        self.lblTimer.setText("")
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName("lblTimer")

        self.retranslateUi(Dialog_TimerCook)
        QtCore.QMetaObject.connectSlotsByName(Dialog_TimerCook)

    def retranslateUi(self, Dialog_TimerCook):
        _translate = QtCore.QCoreApplication.translate
        Dialog_TimerCook.setWindowTitle(_translate("Dialog_TimerCook", "Cook - Food Vending Machine"))
        self.progressBar.setFormat(_translate("Dialog_TimerCook", "%p%"))
        self.label.setText(_translate("Dialog_TimerCook", "ขณะนี้กำลังอุ่นอาหาร"))
import icon_rc
